<?php

return [
    [
    'title' => 'Locations',
    'icon' => 'fas fa-map-marker-alt',
    'url' => 'hr/locations',
    'permission' => 'view_location',
],
    [
    'itemType' => 'item-separator',
    'title' => '<h6 class="ps-3 mt-4 mb-2 text-uppercase text-xs font-weight-bolder opacity-6 group-title">Settings</h6>',
    'url' => null,
],
    [
    'title' => 'Companies',
    'icon' => 'fas fa-building',
    'url' => 'hr/companies',
    'permission' => 'manage-system',
    'groupTitle' => 'Settings',
],
    [
    'itemType' => 'item-separator',
    'title' => '<h6 class="ps-3 mt-4 mb-2 text-uppercase text-xs font-weight-bolder opacity-6 group-title">Organization</h6>',
    'url' => null,
],
    [
    'title' => 'Departments',
    'icon' => 'fas fa-sitemap',
    'url' => 'hr/departments',
    'permission' => 'view_department',
    'groupTitle' => 'Organization',
],
    [
    'title' => 'Job Titles',
    'icon' => 'fas fa-briefcase',
    'url' => 'hr/job-titles',
    'permission' => 'view_job_title',
    'groupTitle' => 'Organization',
],
    [
    'title' => 'Employees',
    'icon' => 'fas fa-user-friends',
    'url' => 'hr/employees',
    'permission' => 'view_employee',
],
    [
    'title' => 'Job Information',
    'icon' => 'fas fa-briefcase',
    'url' => 'hr/employee-positions',
    'permission' => 'view_employee_position',
],
    [
    'title' => 'Profiles',
    'icon' => 'fas fa-user-circle',
    'url' => 'hr/employee-profiles',
    'permission' => 'view_employee_profile',
],
    [
    'itemType' => 'item-separator',
    'title' => '<h6 class="ps-3 mt-4 mb-2 text-uppercase text-xs font-weight-bolder opacity-6 group-title">People Management</h6>',
    'url' => null,
],
    [
    'title' => 'Documents',
    'icon' => 'fas fa-file',
    'url' => 'hr/documents',
    'permission' => 'view_document',
    'groupTitle' => 'People Management',
],
    [
    'title' => 'Pay Schedules',
    'icon' => 'fas fa-calendar-alt',
    'url' => 'hr/pay-schedules',
    'permission' => 'view_pay_schedule',
],
    [
    'title' => 'Employees',
    'icon' => 'fas fa-user-tie',
    'url' => 'hr/employee-payroll-profiles',
    'permission' => 'view_employee_payroll_profile',
],
    [
    'title' => 'Pay Runs',
    'icon' => 'fas fa-file-invoice-dollar',
    'url' => 'hr/payroll-runs',
    'permission' => 'view_payroll_run',
],
    [
    'title' => 'Payslips',
    'icon' => 'fas fa-receipt',
    'url' => 'hr/payroll-payslips',
    'permission' => 'view_payroll_payslip',
],
    [
    'title' => 'Leave Types',
    'icon' => 'fas fa-tags',
    'url' => 'hr/leave-types',
    'permission' => 'view_leave_type',
],
    [
    'title' => 'Leave Requests',
    'icon' => 'fas fa-calendar-alt',
    'url' => 'hr/leave-requests',
    'permission' => 'view_leave_request',
],
    [
    'title' => 'Leave Balances',
    'icon' => 'fas fa-scale-balanced',
    'url' => 'hr/leave-balances',
    'permission' => 'view_leave_balance',
],
    [
    'title' => 'Leave Approvers',
    'icon' => 'fas fa-user-shield',
    'url' => 'hr/leave-approvers',
    'permission' => 'view_leave_approver',
],
    [
    'itemType' => 'item-separator',
    'title' => '<h6 class="ps-3 mt-4 mb-2 text-uppercase text-xs font-weight-bolder opacity-6 group-title">Scheduling</h6>',
    'url' => null,
],
    [
    'title' => 'Shifts',
    'icon' => 'fas fa-calendar-day',
    'url' => 'hr/shifts',
    'permission' => 'view_shift',
    'groupTitle' => 'Scheduling',
],
    [
    'itemType' => 'item-separator',
    'title' => '<h6 class="ps-3 mt-4 mb-2 text-uppercase text-xs font-weight-bolder opacity-6 group-title">Time Tracking</h6>',
    'url' => null,
],
    [
    'title' => 'Attendance',
    'icon' => 'fas fa-user-clock',
    'url' => 'hr/attendances',
    'permission' => 'view_attendance',
    'groupTitle' => 'Time Tracking',
],
    [
    'title' => 'Shift Schedules',
    'icon' => 'fas fa-calendar-alt',
    'url' => 'hr/shift-schedules',
    'permission' => 'view_shift_schedule',
    'groupTitle' => 'Scheduling',
],
    [
    'title' => 'Clock Events',
    'icon' => 'fas fa-clock',
    'url' => 'hr/clock-events',
    'permission' => 'view_clock_event',
    'groupTitle' => 'Time Tracking',
],
    [
    'title' => 'Work Sessions',
    'icon' => 'fas fa-history',
    'url' => 'hr/attendance-sessions',
    'permission' => 'view_attendance_session',
    'groupTitle' => 'Time Tracking',
],
    [
    'title' => 'Holiday Calendars',
    'icon' => 'fas fa-calendar-alt',
    'url' => 'hr/holiday-calendars',
    'permission' => 'view_holiday_calendar',
    'groupTitle' => 'Scheduling',
],
    [
    'title' => 'Holidays',
    'icon' => 'fas fa-gift',
    'url' => 'hr/holidays',
    'permission' => 'view_holiday',
    'groupTitle' => 'Scheduling',
],
];
